# Generated by Django 2.0.6 on 2018-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subby', '0029_auto_20180803_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hello1', max_length=20),
            preserve_default=False,
        ),
    ]
